dist: bionic

language: python
python: 3.7

env:
  global:
    - HELTECCOMMIT=ded98af3c725e5abe844b6adb20a3d1c70b5da34
    - AUNITCOMMIT=acacc8c1d17b25e2b48432ba477f197318ce82ea
  matrix:
    - PLATFORM=esp8266
      HARDWARE=esp8266com/esp8266
      COREGIT=https://github.com/esp8266/Arduino.git
      CORECOMMIT=b6e58301af12c51b28d07e4485060504ef2b293a
      BOARD='--board esp8266com:esp8266:nodemcuv2  --pref custom_xtal=nodemcuv2_80 --pref custom_eesz=nodemcuv2_4M1M'
    - PLATFORM=esp32
      HARDWARE=espressif/esp32
      COREGIT=https://github.com/espressif/arduino-esp32.git
      CORECOMMIT=7a574399b17e552800459e3eafb72d9158c05968
      BOARD='--board espressif:esp32:heltec_wifi_kit_32 --pref custom_FlashFreq=heltec_wifi_kit_32_80'
    - PLATFORM=nrf52
      BOARD='--board adafruit:nrf52:feather52832 --pref custom_softdevice=feather52832_s132v6'
      NRF52VERSION=0.13.0

services:
  - xvfb

before_install:
  - sudo iptables -A INPUT -p udp -m udp --dport 5353 -j DROP # https://github.com/per1234/arduino-ci-script/issues/1

install:
  - |
    : download Arduino IDE
    mkdir -p $HOME/arduino_ide; cd $HOME/arduino_ide
    curl -L http://downloads.arduino.cc/arduino-1.8.9-linux64.tar.xz | tar xJ --strip 1
    export PATH="$HOME/arduino_ide:$PATH"
  - |
    : download platform
    if [[ $PLATFORM == nrf52 ]]; then
      sudo dpkg --add-architecture i386
      sudo apt-get update
      sudo apt-get install libc6:i386
      pip install adafruit-nrfutil
      arduino --pref "boardsmanager.additional.urls=https://www.adafruit.com/package_adafruit_index.json" --save-prefs
      arduino --install-boards adafruit:nrf52:$NRF52VERSION
    elif [[ $PLATFORM =~ ^esp ]]; then
      if [[ $PLATFORM == esp32 ]]; then
        pip install pyserial
      fi
      mkdir -p $HOME/Arduino/hardware/$HARDWARE
      cd $HOME/Arduino/hardware/$HARDWARE
      git init
      git fetch $COREGIT
      git -c advice.detachedHead=false checkout $CORECOMMIT
      git submodule update --init
      cd tools
      python get.py
    fi
  - |
    : download Arduino libraries
    mkdir -p $HOME/Arduino/libraries
    cd $HOME/Arduino/libraries
    if [[ $PLATFORM == esp32 ]]; then
      curl -L https://github.com/HelTecAutomation/Heltec_ESP32/archive/$HELTECCOMMIT.tar.gz | tar xz
      mv Heltec_ESP32-$HELTECCOMMIT Heltec_ESP32
    fi
    curl -L https://github.com/bxparks/AUnit/archive/$AUNITCOMMIT.tar.gz | tar xz
    mv AUnit-$AUNITCOMMIT AUnit

before_script:
  - cp -r $TRAVIS_BUILD_DIR $HOME/Arduino/libraries/esp8266ndn

script:
  - |
    : build examples
    NFAIL=0
    for SKETCH in $(find $TRAVIS_BUILD_DIR -name '*.ino'); do
      echo
      echo
      if [[ -f $(dirname $SKETCH)/skip-$PLATFORM.txt ]]; then
        echo -e '\033[0;34m'Skipping $SKETCH '\033[0m'
        continue
      fi
      BOARDARG=$BOARD
      if [[ -f $(dirname $SKETCH)/board-$PLATFORM.txt ]]; then
        BOARDARG=$(cat $(dirname $SKETCH)/board-$PLATFORM.txt)
      fi
      echo -e '\033[0;36m'Building $SKETCH '\033[0m'
      echo
      arduino --verify $BOARDARG $SKETCH || NFAIL=$((NFAIL+1))
    done
    [[ $NFAIL -eq 0 ]]
